---
# Defined services
define:
  example_service: production AND webhooks
  another_service: another AND service AND docker
  test: test
# Sync time in seconds
sync_interval: 1
# Elasticsearch query configuration
elasticsearch_url: logs.ec2.srcclr.com
elasticsearch_port: 9200
elasticsearch_index: logstash-\* 

 
