---
# Defined services
define:
  librarian: librarian AND production
  prod_webhooks: docker AND production AND webhooks
# Sync time in seconds
sync_interval: 5 
sync_depth: 10
# Elasticsearch query configuration
elasticsearch_url: logs.ec2.srcclr.com
elasticsearch_port: 9200
elasticsearch_index: logstash-\* 

 
