---
# Defined services
define:
  my_example_service: some_value AND another_value
  another_example_service: docker AND haproxy
# Sync time in seconds
sync_interval: 5 
sync_depth: 10
# Elasticsearch query configuration
elasticsearch_url: my.elasticsearch.com 
elasticsearch_port: 9200
# Not actually using this atm
elasticsearch_index: logstash-\* 

 
